version: '3.8'

services:
  bot:
    restart: always
    build: tinkoff-bot
    depends_on:
      - modelserver
      - mongo
    environment:
      - BOT_TELETGRAM_TOKEN=value
      - BOT_MONGODB_URL=mongodb://localhost:27017
      - BOT_MONGODB_NAME=BOT
      - BOT_MODEL_SERVER_URL=http://localhost:80/
    ports:
      - "80:80"
      - "27017:27017"
    network_mode: host
  modelserver:
    build: tinkoff-model-server
    ports:
      - "80:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - MODEL_MODEL_NAME=denisgr04/guap
      - MODEL_DEVICE=auto
      - MODEL_CONTEXT_WINDOW=2048
      - MODEL_MAX_NEW_TOKEN=256
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
volumes:
  mongo:
